services:
  container:
    container_name: container
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - '2375:2375'
    command: >
      dockerd
      --tls=false
      --host=tcp://0.0.0.0:2375
    # --host=unix:///var/run/docker.sock
    restart: unless-stopped
